### ISSUE TITLE
En tant qu'utilisateur, je veux pouvoir me connecter à l'application en utilisant mes identifiants, pour pouvoir acceder à l'application.

### ISSUE THREAD

**Issue by dunialydie** [Muking3/Gestion-des-Inventaires#14]

**Comment by dunialydie** [comment]
## Critères d'acceptation

- [ ]L'utilisateur peut s'authentifier en utilisant un nom d'utilisateur et un mot de passe valides.
- [ ]Un utilisateur authentifié voit son nom d'utilisateur affiché dans l'interface.
- [ ]l'authentification échoue si le nom d'utilisateur ou le mot de passe est incorrect.
