### ISSUE TITLE
En tant qu'administrateur, je veux pouvoir gérer les comptes utilisateurs (creer, desactiver et supprimer des comptes utilisateurs), pour controler l'accès à l'application.

### ISSUE THREAD

**Issue by dunialydie** [Muking3/Gestion-des-Inventaires#16]

**Comment by dunialydie** [comment]
## Critères d'acceptation

- [ ]Un administrateur peut créer un nouveau compte utilisateur en spécifiant un nom d'utilisateur, un mot de passe et un rôle.
- [ ]Un administrateur peut modifier les informations d'un compte utilisateur existant.
- [ ]Un administrateur peut désactiver ou supprimer un compte utilisateur.
